site_name: GATE Docs
site_url: https://dm4ml.github.io/gate/
repo_url: https://github.com/dm4ml/gate
repo_name: dm4ml/gate
remote_branch: gh-pages
nav:
  - Home: index.md
  - Example: example.md
  - API Reference: api.md
  - How it Works: how-it-works.md

theme:
  name: material
  icon:
    logo: material/gate
    repo: fontawesome/brands/git-alt
  favicon: images/logo.png
  extra_files:
    - images/
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: orange
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Fira Sans
    code: Fira Code
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.follow
    - header.autohide
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings
  - autorefs

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg